name: Development CI Workflow

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    build:
        name: Execute Repository CI
        timeout-minutes: 15
        runs-on: ${{ matrix.os }}
        # To use Remote Caching, uncomment the next lines and follow the steps below.
        # env:
        #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        strategy:
            matrix:
                os: [ubuntu-latest]

        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}

            - name: Check out code
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 7.9.0
                  run_install: false

            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-
            - name: Install dependencies
              run: pnpm install --ignore-scripts --frozen-lockfile

            - name: Build packages
              run: pnpm build --filter "./packages/**"

            - name: Lint
              run: pnpm lint

            - name: Type Check
              run: pnpm type-check

            - name: Test
              run: pnpm test
